### ISSUE TITLE
我是小白，这个项目在linux上能部署吗？弄到最后一步报错了。

### ISSUE THREAD

**Issue by ecnuHL** [YYuX-1145/Bert-VITS2-Integration-package#14]
python train_ms.py -c ./configs\config.json
Traceback (most recent call last):
  File "train_ms.py", line 26, in <module>
    from models import (
  File "/home/lhuang/Bert-VITS2-Integration-package-main/models.py", line 10, in <module>
    import monotonic_align
  File "/home/lhuang/Bert-VITS2-Integration-package-main/monotonic_align/__init__.py", line 3, in <module>
    from .monotonic_align.core import maximum_path_c
    import monotonic_align
  File "/home/lhuang/Bert-VITS2-Integration-package-main/monotonic_align/__init__.pyc ./configs\config.json", line 3, in <module>
    from .monotonic_align.core import maximum_path_c
ModuleNotFoundError: No module named 'monotonic_align.monotonic_align.core'

**Comment by YYuX-1145** [comment]
finetune里有构建单调对齐搜索的方法。另外你可以从原项目里导入不需要c的版本

**Comment by ecnuHL** [comment]
> 首先非常感谢你的解答，但是我这一点都理解不了这个意思啊。大佬，是要改哪方面的代码吗？能不能给我一个具体的建议或者方向，非常感谢。

**Comment by YYuX-1145** [comment]
> > 首先非常感谢你的解答，但是我这一点都理解不了这个意思啊。大佬，是要改哪方面的代码吗？能不能给我一个具体的建议或者方向，非常感谢。
https://github.com/Plachtaa/VITS-fast-fine-tuning/blob/main/LOCAL.md
小白还用Linux？那么我还是建议你去部署原项目。制作本整合包的目的是让原项目在Windows上运行，对于云训练产生的其余问题我不解答
