### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by youxingtian** [YYuX-1145/Bert-VITS2-Integration-package#25]
在mac下推理报这个错误，麻烦作者给指导一下！
在网上查了一下这个错误，说是模型文件每下载完，但是我确定是下载完了的，本地文件大小和服务器模型训练完成保存的文件大小是一模一样的
Traceback (most recent call last):
  File "/Users/youbo/PycharmProjects/demo/tts_demo/Bert-VITS2-Integration-package/inference_cmd.py", line 114, in <module>
    _ = utils.load_checkpoint(args.model_dir, net_g, None, skip_optimizer=True)
  File "/Users/youbo/PycharmProjects/demo/tts_demo/Bert-VITS2-Integration-package/utils.py", line 21, in load_checkpoint
    checkpoint_dict = torch.load(checkpoint_path, map_location='cpu')
  File "/Users/youbo/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/Users/youbo/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

**Comment by YYuX-1145** [comment]
1.本整合包适用于Windows。2.inference_cmd.py并非本整合包内的文件。3.我不是原作者，没有修改训练和推理直接相关的代码，无法解答该问题。
