### ISSUE TITLE
RuntimeError: The expanded size of the tensor (32) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 32].  Tensor sizes: [192, 0]

### ISSUE THREAD

**Issue by youxingtian** [YYuX-1145/Bert-VITS2-Integration-package#27]
这个报错是什么原因引起的呀，麻烦作者给指导一下
```Traceback (most recent call last):
  File "/data/xxx/ai_algorithm/tts_demo/Bert-VITS2-Integration-package-main-16/train_ms.py", line 402, in <module>
    main()
  File "/data/xxx/ai_algorithm/tts_demo/Bert-VITS2-Integration-package-main-16/train_ms.py", line 60, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/data/xxx/miniconda3/envs/tts/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/xxx/miniconda3/envs/tts/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/data/xxx/miniconda3/envs/tts/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/xxx/miniconda3/envs/tts/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/xxx/ai_algorithm/tts_demo/Bert-VITS2-Integration-package-main-16/train_ms.py", line 193, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d, net_dur_disc], [optim_g, optim_d, optim_dur_disc], [scheduler_g, scheduler_d, scheduler_dur_disc], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/data/xxx/ai_algorithm/tts_demo/Bert-VITS2-Integration-package-main-16/train_ms.py", line 231, in train_and_evaluate
    (z, z_p, m_p, logs_p, m_q, logs_q), (hidden_x, logw, logw_) = net_g(x, x_lengths, spec, spec_lengths, speakers, tone, language, bert)
  File "/data/xxx/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/xxx/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data/xxx/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/data/xxx/miniconda3/envs/tts/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/xxx/ai_algorithm/tts_demo/Bert-VITS2-Integration-package-main-16/models.py", line 680, in forward
    z_slice, ids_slice = commons.rand_slice_segments(z, y_lengths, self.segment_size)
  File "/data/xxx/ai_algorithm/tts_demo/Bert-VITS2-Integration-package-main-16/commons.py", line 63, in rand_slice_segments
    ret = slice_segments(x, ids_str, segment_size)
  File "/data/xxx/ai_algorithm/tts_demo/Bert-VITS2-Integration-package-main-16/commons.py", line 53, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (32) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 32].  Tensor sizes: [192, 0]
```

**Comment by YYuX-1145** [comment]
#7 我不能确定具体原因，看看这个？
