### ISSUE TITLE
bert_gen.py报错 huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../bert/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by ANGJustinl** [YYuX-1145/Bert-VITS2-Integration-package#29]
如题,已经完成chinese_bert.py 的测试,主函数运行正常,对数据集的清理与重采样也完成
![image](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/96008766/919d210a-aace-493c-94ba-eec2daeba787)
![image](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/96008766/7c06522c-1ae6-435e-9f7b-b6fad405a56a)

报错如下
![image](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/96008766/2e254779-6dbc-408c-a877-cccbe7f32afd)

_(venv) F:\TTS\Bert-VITS2>python bert_gen.py
  0%|                                                                                         | 0/1057 [00:07<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 34, in process_line
    bert = torch.load(bert_path)
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/huanglongyidou/vo_LYYCOP001_1905703_itto_29.bert.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 37, in process_line
    bert = get_bert(text, word2ph, language_str, torch.device("cuda:0"))
  File "F:\TTS\Bert-VITS2\text\__init__.py", line 22, in get_bert
    from .chinese_bert import get_bert_feature as zh_bert
  File "F:\TTS\Bert-VITS2\text\chinese_bert.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained("../bert/chinese-roberta-wwm-ext-large")
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 686, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 519, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\transformers\utils\hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../bert/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 58, in <module>
    for _ in tqdm(pool.imap_unordered(process_line, lines), total=len(lines)):
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 870, in next
    raise value
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../bert/chinese-roberta-wwm-ext-large'. Use `repo_type` argument if needed._

**Comment by ANGJustinl** [comment]
![image](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/96008766/71321492-56f1-41a2-b0ea-e43a48d03d78)

**Comment by ANGJustinl** [comment]
而且现在这个报错是我试着修了一下的报错，源bert_gen.py运行结果为
![image](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/96008766/e7bfe51e-6af9-43bc-84e9-8680a84b58c9)

(venv) F:\TTS\Bert-VITS2>python bert_gen.py
  0%|                                                                                         | 0/1057 [00:04<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 35, in process_line
    bert = torch.load(bert_path)
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/huanglongyidou/vo_SDEQ002_2_itto_10.bert.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 38, in process_line
    bert = get_bert(text, word2ph, language_str, device)
UnboundLocalError: local variable 'device' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 59, in <module>
    for _ in tqdm(pool.imap_unordered(process_line, lines), total=len(lines)):
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 870, in next
    raise value
UnboundLocalError: local variable 'device' referenced before assignment

(venv) F:\TTS\Bert-VITS2>python bert_gen.py
  0%|                                                                                         | 0/1057 [00:03<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 35, in process_line
    bert = torch.load(bert_path)
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/huanglongyidou/vo_SDEQ002_2_itto_10.bert.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 38, in process_line
    bert = get_bert(text, word2ph, language_str, device)
UnboundLocalError: local variable 'device' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\TTS\Bert-VITS2\bert_gen.py", line 59, in <module>
    for _ in tqdm(pool.imap_unordered(process_line, lines), total=len(lines)):
  File "F:\TTS\Bert-VITS2\venv\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 870, in next
    raise value
UnboundLocalError: local variable 'device' referenced before assignment

**Comment by YYuX-1145** [comment]
你都对整合包改了些啥？

**Comment by bihailantian655** [comment]
标题的 报错是怎么解决的呢？
