### ISSUE TITLE
云端训练报错

### ISSUE THREAD

**Issue by FireFlieStudio** [YYuX-1145/Bert-VITS2-Integration-package#31]
```-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/Bert-VITS2-Integration-Package/train_ms.py", line 193, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d, net_dur_disc], [optim_g, optim_d, optim_dur_disc], [scheduler_g, scheduler_d, scheduler_dur_disc], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/root/Bert-VITS2-Integration-Package/train_ms.py", line 217, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers, tone, language, bert) in tqdm(enumerate(train_loader)):
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/root/Bert-VITS2-Integration-Package/data_utils.py", line 212, in __call__
    spec_padded[i, :, :spec.size(1)] = spec
RuntimeError: expand(torch.FloatTensor{[2, 1025, 413]}, size=[1025, 1025]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)
```

我想问下这是啥问题啊，头疼

**Comment by FireFlieStudio** [comment]
我的数据集是用的红血球大佬的崩铁三月七的数据集,而且大于10s的都挑出来的,低于整体wav长度平均值的也挑出来了QAQ

**Comment by FireFlieStudio** [comment]
看了些文档,又折腾了一下,重采样解决了( 什么蠢B
