### ISSUE TITLE
训练报错请问是什么原因造成的呢？找了很久找不到问题，能否给一个解决思路！

### ISSUE THREAD

**Issue by timosss** [YYuX-1145/Bert-VITS2-Integration-package#42]
raceback (most recent call last):
  File "train_ms.py", line 402, in <module>
    main()
  File "train_ms.py", line 60, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/Bert-VITS2-Integration-Package/train_ms.py", line 193, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d, net_dur_disc], [optim_g, optim_d, optim_dur_disc], [scheduler_g, scheduler_d, scheduler_dur_disc], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/root/Bert-VITS2-Integration-Package/train_ms.py", line 231, in train_and_evaluate
    (z, z_p, m_p, logs_p, m_q, logs_q), (hidden_x, logw, logw_) = net_g(x, x_lengths, spec, spec_lengths, speakers, tone, language, bert)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/Bert-VITS2-Integration-Package/models.py", line 680, in forward
    z_slice, ids_slice = commons.rand_slice_segments(z, y_lengths, self.segment_size)
  File "/root/Bert-VITS2-Integration-Package/commons.py", line 63, in rand_slice_segments
    ret = slice_segments(x, ids_str, segment_size)
  File "/root/Bert-VITS2-Integration-Package/commons.py", line 53, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (32) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 32].  Tensor sizes: [192, 0]

**Comment by studyhardstudyhard** [comment]
我也出现这个，有人解决了吗

**Comment by youxingtian** [comment]
梅尔频谱本身需要有一个加窗的过程，实现不同（我只看过librosa的，他这个是用torch的，原理应该类似），你的音频文件必须要至少达到1帧长+窗口时长才能有结果，否则就会返回空。
一个简单的建议：在数据清洗时直接干掉所有2秒内的音频，本来短时样本的质量就偏低。
