### ISSUE TITLE
加载配置出错

### ISSUE THREAD

**Issue by FlameHaze-ZY** [YYuX-1145/Bert-VITS2-Integration-package#46]
按照步骤设定好实验并投入音频点击加载训练配置出错错误如下

Traceback (most recent call last):
  File "F:\Bert-VITS2-Integration-Package.release\2.0.2\Bert-VITS2-Integration-Pack-v2.0.2\manager202.py", line 103, in p0_load_cfg
    return p0_status.update(value=current_yml) ,'Success'
AttributeError: 'TextArea' object has no attribute 'update'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\conda\envs\bert_vist\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\conda\envs\bert_vist\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\conda\envs\bert_vist\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\utils.py", line 673, in wrapper
    response = f(*args, **kwargs)
  File "F:\Bert-VITS2-Integration-Package.release\2.0.2\Bert-VITS2-Integration-Pack-v2.0.2\manager202.py", line 105, in p0_load_cfg
    return p0_status.update(value=current_yml),error
AttributeError: 'TextArea' object has no attribute 'update'
Traceback (most recent call last):
  File "F:\Bert-VITS2-Integration-Package.release\2.0.2\Bert-VITS2-Integration-Pack-v2.0.2\manager202.py", line 103, in p0_load_cfg
    return p0_status.update(value=current_yml) ,'Success'
AttributeError: 'TextArea' object has no attribute 'update'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\conda\envs\bert_vist\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\conda\envs\bert_vist\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\conda\envs\bert_vist\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\utils.py", line 673, in wrapper
    response = f(*args, **kwargs)
  File "F:\Bert-VITS2-Integration-Package.release\2.0.2\Bert-VITS2-Integration-Pack-v2.0.2\manager202.py", line 105, in p0_load_cfg
    return p0_status.update(value=current_yml),error
AttributeError: 'TextArea' object has no attribute 'update'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "E:\conda\envs\bert_vist\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by YYuX-1145** [comment]
从代码逻辑上来看配置文件应该已经成功加载了，只是右侧无法正常显示。根据报错，TextArea（也就是右边的文字框）内容不能被更新，可能是和你的gradio版本有关，你是自己的环境，我这里是正常的

**Comment by FlameHaze-ZY** [comment]
感谢排查，能请问下您那边的环境使用的gradio的版本吗？我使用的最新的版本似乎不行

**Comment by YYuX-1145** [comment]
3.39.0，实在不行把它的属性改成Textbox

**Comment by FlameHaze-ZY** [comment]
好吧确实是是这个原因换成3.39.0可以加载了，感谢
