### ISSUE TITLE
一点训练就报错，求大神怎么解决？

### ISSUE THREAD

**Issue by bibobox** [YYuX-1145/Bert-VITS2-Integration-package#58]
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                            | 0/2 [00:00<?, ?it/s]12-28 01:42:31 WARNING  | data_utils.py:157 | Bert load Failed
12-28 01:42:31 WARNING  | data_utils.py:157 | Bert load Failed
12-28 01:42:31 WARNING  | data_utils.py:158 | unpickling stack underflow
12-28 01:42:31 WARNING  | data_utils.py:158 | unpickling stack underflow
  0%|                                                                                            | 0/2 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "train_ms.py", line 840, in <module>
    run()
  File "train_ms.py", line 361, in run
    train_and_evaluate(
  File "train_ms.py", line 423, in train_and_evaluate
    for batch_idx, (
  File "C:\AI\AIsound\Bert-VITS2-2.3\venv\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\AI\AIsound\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "C:\AI\AIsound\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\AI\AIsound\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\AI\AIsound\Bert-VITS2-2.3\venv\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\AI\AIsound\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\AI\AIsound\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\AI\AIsound\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\AI\AIsound\Bert-VITS2-2.3\data_utils.py", line 182, in __getitem__
    return self.get_audio_text_speaker_pair(self.audiopaths_sid_text[index])
  File "C:\AI\AIsound\Bert-VITS2-2.3\data_utils.py", line 91, in get_audio_text_speaker_pair
    bert, ja_bert, en_bert, phones, tone, language = self.get_text(
  File "C:\AI\AIsound\Bert-VITS2-2.3\data_utils.py", line 161, in get_text
    bert = bert_ori
UnboundLocalError: local variable 'bert_ori' referenced before assignment

**Comment by YYuX-1145** [comment]
预处理都成功了么？
