### ISSUE TITLE
0903的包还是开始训练就报错

### ISSUE THREAD

**Issue by webchong** [YYuX-1145/Bert-VITS2-Integration-package#6]
D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package>%PYTHON% train_ms.py -c ./configs\config.json
INFO:OUTPUT_MODEL:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 52, 'epochs': 1000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 16384, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'use_mel_posterior_encoder': False, 'training_files': 'filelists/train.list', 'validation_files': 'filelists/val.list', 'max_wav_value': 32768.0, 'sampling_rate': 44100, 'filter_length': 2048, 'hop_length': 512, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 1, 'cleaned_text': True, 'spk2id': {'tou': 0}}, 'model': {'use_spk_conditioned_encoder': True, 'use_noise_scaled_mas': True, 'use_mel_posterior_encoder': False, 'use_duration_discriminator': True, 'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'model_dir': './logs\\./OUTPUT_MODEL', 'cont': False}
WARNING:OUTPUT_MODEL:D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
skipped:  27 , total:  522
skipped:  0 , total:  4
Using noise scaled MAS for VITS2
Using duration discriminator for VITS2
256 2
256 2
256 2
256 2
256 2
./logs\./OUTPUT_MODEL\DUR_0.pth
error, norm_1.gamma is not in the checkpoint
error, norm_1.beta is not in the checkpoint
error, norm_2.gamma is not in the checkpoint
error, norm_2.beta is not in the checkpoint
error, cond.weight is not in the checkpoint
error, cond.bias is not in the checkpoint
load
INFO:OUTPUT_MODEL:Loaded checkpoint './logs\./OUTPUT_MODEL\DUR_0.pth' (iteration 694)
./logs\./OUTPUT_MODEL\G_0.pth
error, emb_g.weight is not in the checkpoint
load
INFO:OUTPUT_MODEL:Loaded checkpoint './logs\./OUTPUT_MODEL\G_0.pth' (iteration 0)
./logs\./OUTPUT_MODEL\D_0.pth
load
INFO:OUTPUT_MODEL:Loaded checkpoint './logs\./OUTPUT_MODEL\D_0.pth' (iteration 0)
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train_ms.py", line 402, in <module>
    main()
  File "train_ms.py", line 60, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\train_ms.py", line 193, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d, net_dur_disc], [optim_g, optim_d, optim_dur_disc], [scheduler_g, scheduler_d, scheduler_dur_disc], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\train_ms.py", line 217, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers, tone, language, bert) in tqdm(enumerate(train_loader)):
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "D:\Bert-VITS2-Integration-Package\Bert-VITS2-Integration-Package\data_utils.py", line 212, in __call__
    spec_padded[i, :, :spec.size(1)] = spec
RuntimeError: expand(torch.FloatTensor{[2, 1025, 316]}, size=[2, 1025]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)

前三步好好的，训练就出错了，之前的包是归零的问题

**Comment by YYuX-1145** [comment]
删除模型输出目录里的全部文件再试试？

**Comment by YYuX-1145** [comment]
有没有删掉原来处理音频产生的bert文件？

**Comment by webchong** [comment]
> 有没有删掉原来处理音频产生的bert文件？
删除了bert目录下的所有文件后还是一样的报错代码

**Comment by webchong** [comment]
音频目录下的所有.bert.pt都在，没有被自动删除过

**Comment by webchong** [comment]
包下载下来的时候custom_character_voice下面是干净的，没有其他音频处理文件，都是前三步产生的文件

**Comment by YYuX-1145** [comment]
> 包下载下来的时候custom_character_voice下面是干净的，没有其他音频处理文件，都是前三步产生的文件

我是说，如果整合包更新了的话，就需要删除原来的bert文件重新生成

**Comment by webchong** [comment]
> 

新下载的0903的整合包里是没有其他bert文件的，标注了以后再处理了文本，bert文件都全部重新生成了的，bert内的编码也是正常的，就是第四部卡在训练报错

**Comment by wy1042033725** [comment]
遇到同样的问题了，如何解决呢？急。。

**Comment by YYuX-1145** [comment]
你们这个错误我依然没有遇到过。不过上一个遇到这种奇怪的错误的人说是他自己的问题并且已经解决了，具体的原因他还没回复我，可能和数据集有关系吧，确保不要超长或者有过长的静音段。

**Comment by qq1044083166** [comment]
> 你们这个错误我依然没有遇到过。不过上一个遇到这种奇怪的错误的人说是他自己的问题并且已经解决了，具体的原因他还没回复我，可能和数据集有关系吧，确保不要超长或者有过长的静音段。

我也出现了这个问题，最开始我的数据集为双声道，报错与上述相同。 但将数据集处理为单声道后，训练便可以正常运行。 也许是音频声道数导致的问题

**Comment by qq1044083166** [comment]
Up主 在整合包加个bat文件吧 方便开启tensorboard
代码如下：
chcp 65001
@echo off

echo 正在启动Tensorboard...
echo 如果看到输出了一条网址（大概率是localhost:6006）就可以访问该网址进入Tensorboard了


.\venv\python.exe -m tensorboard.main --logdir=logs\OUTPUT_MODEL

pause

**Comment by YYuX-1145** [comment]
> Up主 在整合包加个bat文件吧 方便开启tensorboard 代码如下： chcp 65001 @echo off
> 
> echo 正在启动Tensorboard... echo 如果看到输出了一条网址（大概率是localhost:6006）就可以访问该网址进入Tensorboard了
> 
> .\venv\python.exe -m tensorboard.main --logdir=logs\OUTPUT_MODEL
> 
> pause

好的 总之感谢反馈了，我会确认一下问题

**Comment by YYuX-1145** [comment]
> > 你们这个错误我依然没有遇到过。不过上一个遇到这种奇怪的错误的人说是他自己的问题并且已经解决了，具体的原因他还没回复我，可能和数据集有关系吧，确保不要超长或者有过长的静音段。
> 
> 我也出现了这个问题，最开始我的数据集为双声道，报错与上述相同。 但将数据集处理为单声道后，训练便可以正常运行。 也许是音频声道数导致的问题

那么问题来了，我测试下来short_audio_transcribe是会把双声道音频转为单声道的。照理来说这么按流程训练也不会报这个错呀？

**Comment by webchong** [comment]
果然，替换为单声道音频后，不再报错，可以正常训练了。。。

**Comment by qq1044083166** [comment]
OK！

**Comment by YYuX-1145** [comment]
> 果然，替换为单声道音频后，不再报错，可以正常训练了。。。

请问您是用内置的脚本预处理的么？但是我看处理完以processed开头的音频在au里显示为单声道。

**Comment by webchong** [comment]
> 

我因为切片的音频数量太多了，而且au批量转换后体积比较大，所以我用格式工厂批量转的单声道

**Comment by YYuX-1145** [comment]
> > 
> 
> 我因为切片的音频数量太多了，而且au批量转换后体积比较大，所以我用格式工厂批量转的单声道

破案了
