### ISSUE TITLE
worker 8  ，batch1

### ISSUE THREAD

**Issue by bihailantian655** [YYuX-1145/Bert-VITS2-Integration-package#66]
跟  worker   不知道有关系么 ，  batch 设置为1  就会报这个错误 ，batch 高 ，占用现存太大 

Traceback (most recent call last):
  File "train_ms.py", line 840, in <module>
    run()
  File "train_ms.py", line 361, in run
    train_and_evaluate(
  File "train_ms.py", line 560, in train_and_evaluate
    loss_slm = wl.discriminator(
  File "I:\Bert-VITS2-2.3\losses.py", line 108, in discriminator
    wav_embeddings = self.wavlm(
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\transformers\models\wavlm\modeling_wavlm.py", line 1231, in forward
    extract_features = self.feature_extractor(input_values)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\transformers\models\wavlm\modeling_wavlm.py", line 369, in forward
    hidden_states = conv_layer(hidden_states)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\transformers\models\wavlm\modeling_wavlm.py", line 264, in forward
    hidden_states = self.conv(hidden_states)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\nn\modules\conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [512, 1, 10], expected input[1, 5945, 1] to have 1 channels, but got 5945 channels instead

**Comment by YYuX-1145** [comment]
看上去是一个原项目的bug,但是建议bs至少为2，否则效果很有可能会很糟糕

**Comment by bihailantian655** [comment]
batch2   500  轮保存一次。训练两个 人声，差不多都是1500 轮之前报错。
![{D2893F9D-81B8-4065-8842-D19C7B81BB3C}](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/35267721/7777a257-35ce-4903-99cf-956551685daa)

![{C7BE54F0-7F6E-428d-9B7F-F951D946D884}](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/35267721/6d94078c-2509-47ba-92f9-dc1da4495c15)


![{2F690333-0B3D-4bda-9048-D79786BB89F3}](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/35267721/633fccff-08a1-456c-8a61-d2011ee87669)

继续训练报这个错误
![{C38FD995-3909-40fe-89E4-F5EF1C3BDC12}](https://github.com/YYuX-1145/Bert-VITS2-Integration-package/assets/35267721/d66a247a-f481-49b7-8a64-d854c1ff0091)





INFO:models:[2.0433237552642822, 2.807363748550415, 9.663138389587402, 23.075393676757812, 4.142553329467773, 1.9929174184799194, 1000, 9.995001124850014e-05]
Evaluating ...
INFO:models:Saving model and optimizer state at iteration 10 to Data\Bert0\models\G_1000.pth
INFO:models:Saving model and optimizer state at iteration 10 to Data\Bert0\models\D_1000.pth
INFO:models:Saving model and optimizer state at iteration 10 to Data\Bert0\models\WD_1000.pth
INFO:models:Saving model and optimizer state at iteration 10 to Data\Bert0\models\DUR_1000.pth
100%|██████████████████████████████████████████████████████████████████████████████████| 91/91 [02:25<00:00,  1.60s/it]
INFO:models:====> Epoch: 10
100%|██████████████████████████████████████████████████████████████████████████████████| 91/91 [02:10<00:00,  1.43s/it]
INFO:models:====> Epoch: 11
100%|██████████████████████████████████████████████████████████████████████████████████| 91/91 [02:07<00:00,  1.40s/it]
INFO:models:====> Epoch: 12
100%|██████████████████████████████████████████████████████████████████████████████████| 91/91 [02:11<00:00,  1.45s/it]
INFO:models:====> Epoch: 13
100%|██████████████████████████████████████████████████████████████████████████████████| 91/91 [02:11<00:00,  1.44s/it]
INFO:models:====> Epoch: 14
100%|██████████████████████████████████████████████████████████████████████████████████| 91/91 [02:10<00:00,  1.43s/it]
INFO:models:====> Epoch: 15
 48%|███████████████████████████████████████▋                                          | 44/91 [01:03<01:05,  1.40s/it]INFO:models:Train Epoch: 16 [48%]
INFO:models:[2.110910415649414, 2.5810256004333496, 11.354522705078125, 23.514379501342773, 3.143514633178711, 1.6671301126480103, 1500, 9.992002999300117e-05]
Evaluating ...
INFO:models:Saving model and optimizer state at iteration 16 to Data\Bert0\models\G_1500.pth
 48%|███████████████████████████████████████▋                                          | 44/91 [01:14<01:19,  1.68s/it]
Traceback (most recent call last):
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\serialization.py", line 619, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\serialization.py", line 853, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:593] . PytorchStreamWriter failed writing file data/1781: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ms.py", line 840, in <module>
    run()
  File "train_ms.py", line 361, in run
    train_and_evaluate(
  File "train_ms.py", line 698, in train_and_evaluate
    utils.save_checkpoint(
  File "I:\Bert-VITS2-2.3\utils.py", line 133, in save_checkpoint
    torch.save(
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\serialization.py", line 620, in save
    return
  File "I:\Bert-VITS2-2.3\venv\lib\site-packages\torch\serialization.py", line 466, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:424] . unexpected pos 197250880 vs 197250768

**Comment by bihailantian655** [comment]
模型能融合么，多个  只有一个或几个说话人的 模型融合生成  有多个说话人的单个模型，而不用再重复训练。

**Comment by YYuX-1145** [comment]
不能
