### ISSUE TITLE
生成emo文件时报错 求助！

### ISSUE THREAD

**Issue by Electrify27** [YYuX-1145/Bert-VITS2-Integration-package#67]
0%|                                                                                            | 0/2 [00:00<?, ?it/s]E:\AI\Bert-VITS2-2.3\clap_gen.py:34: FutureWarning: Pass sr=48000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  audio = librosa.load(wav_path, 48000)[0]
E:\AI\Bert-VITS2-2.3\clap_gen.py:34: FutureWarning: Pass sr=48000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  audio = librosa.load(wav_path, 48000)[0]
  0%|                                                                                            | 0/2 [00:02<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "E:\AI\Bert-VITS2-2.3\venv\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "E:\AI\Bert-VITS2-2.3\clap_gen.py", line 37, in process_line
    clap = get_clap_audio_feature(audio, device)
  File "E:\AI\Bert-VITS2-2.3\clap_wrapper.py", line 22, in get_clap_audio_feature
    models[device] = ClapModel.from_pretrained("./emotional/clap-htsat-fused").to(
  File "E:\AI\Bert-VITS2-2.3\venv\lib\site-packages\transformers\modeling_utils.py", line 2650, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./emotional/clap-htsat-fused.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "clap_gen.py", line 61, in <module>
    for _ in tqdm(pool.imap_unordered(process_line, lines), total=len(lines)):
  File "E:\AI\Bert-VITS2-2.3\venv\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "E:\AI\Bert-VITS2-2.3\venv\lib\multiprocessing\pool.py", line 868, in next
    raise value
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./emotional/clap-htsat-fused.

**Comment by YYuX-1145** [comment]
主线版无需进行此步，ZH特化版自行安装clap

**Comment by Electrify27** [comment]
> 主线版无需进行此步，ZH特化版自行安装clap

好的感谢
