### ISSUE TITLE
首次训练报错

### ISSUE THREAD

**Issue by GRANTLAOCAI** [YYuX-1145/Bert-VITS2-Integration-package#70]
Using noise scaled MAS for VITS2
Using duration discriminator for VITS2
INFO:models:Loaded checkpoint 'Data\YAOJI\models\DUR_0.pth' (iteration 0)
ERROR:models:emb_g.weight is not in the checkpoint
INFO:models:Loaded checkpoint 'Data\YAOJI\models\G_0.pth' (iteration 0)
PytorchStreamReader failed reading zip archive: failed finding central directory
INFO:models:Loaded checkpoint 'Data\YAOJI\models\WD_0.pth' (iteration 0)
Traceback (most recent call last):
  File "train_ms.py", line 840, in <module>
    run()
  File "train_ms.py", line 335, in run
    scheduler_g = torch.optim.lr_scheduler.ExponentialLR(
  File "E:\Bert-VITS2-2.3\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 586, in __init__
    super().__init__(optimizer, last_epoch, verbose)
  File "E:\Bert-VITS2-2.3\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 42, in __init__
    raise KeyError("param 'initial_lr' is not specified "
KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"

**Comment by YYuX-1145** [comment]
底模损坏了，并且首次训练和继续训练点错了会导致此报错，排查完问题，删除模型输出目录里的全部文件再重新从头开始训练
