### ISSUE TITLE
运行bertgen报系统无法访问此文件。

### ISSUE THREAD

**Issue by DoshideDK** [YYuX-1145/Bert-VITS2-Integration-package#71]
C:\Bert-VITS2-Integration-Package>%PYTHON% bert_gen.py
0it [00:01, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Bert-VITS2-Integration-Package\bert_gen.py", line 35, in process_line
    bert = torch.load(bert_path)
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './custom_character_voice/linlin/processed_0.bert.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\transformers\utils\import_utils.py", line 1130, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Bert-VITS2-Integration-Package\venv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\transformers\models\__init__.py", line 15, in <module>
    from . import (
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\transformers\models\mt5\__init__.py", line 36, in <module>
    from ..t5.tokenization_t5_fast import T5TokenizerFast
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\transformers\models\t5\tokenization_t5_fast.py", line 24, in <module>
    from ...tokenization_utils_fast import PreTrainedTokenizerFast
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\transformers\tokenization_utils_fast.py", line 25, in <module>
    import tokenizers.pre_tokenizers as pre_tokenizers_fast
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\tokenizers\__init__.py", line 80, in <module>
    from .tokenizers import (
ImportError: DLL load failed while importing tokenizers: 系统无法访问此文件。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Bert-VITS2-Integration-Package\venv\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Bert-VITS2-Integration-Package\bert_gen.py", line 38, in process_line
    bert = get_bert(text, word2ph, language_str)
  File "C:\Bert-VITS2-Integration-Package\text\__init__.py", line 21, in get_bert
    from .chinese_bert import get_bert_feature as zh_bert
  File "C:\Bert-VITS2-Integration-Package\text\chinese_bert.py", line 2, in <module>
    from transformers import AutoTokenizer, AutoModelForMaskedLM
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\transformers\utils\import_utils.py", line 1120, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\transformers\utils\import_utils.py", line 1132, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
DLL load failed while importing tokenizers: 系统无法访问此文件。
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bert_gen.py", line 52, in <module>
    for _ in tqdm(pool.imap_unordered(process_line, lines)):
  File "C:\Bert-VITS2-Integration-Package\venv\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Bert-VITS2-Integration-Package\venv\lib\multiprocessing\pool.py", line 868, in next
    raise value
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
DLL load failed while importing tokenizers: 系统无法访问此文件。

**Comment by YYuX-1145** [comment]
环境损坏
