### ISSUE TITLE
FunASR中文打标报错

### ISSUE THREAD

**Issue by DoshideDK** [YYuX-1145/Bert-VITS2-Integration-package#72]
解压更新包，运行安装依赖后，下载1g左右的模型报错

2024-01-26 10:41:36,320 - modelscope - INFO - PyTorch version 2.1.0+cu118 Found.
2024-01-26 10:41:36,320 - modelscope - INFO - Loading ast index from C:\Users\dkh\.cache\modelscope\ast_indexer
2024-01-26 10:41:36,377 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 35763ba37e6c659754a101ddeec5e35f and a total number of 943 components indexed
2024-01-26 10:41:37,512 - modelscope - INFO - Use user-specified model revision: v1.2.4
2024-01-26 10:41:37,845 - modelscope - INFO - initiate model from D:\Bert-VITS2-2.3\transcribe_tools\models\funasr\damo\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-26 10:41:37,845 - modelscope - INFO - initiate model from location D:\Bert-VITS2-2.3\transcribe_tools\models\funasr\damo\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2024-01-26 10:41:37,846 - modelscope - INFO - initialize model from D:\Bert-VITS2-2.3\transcribe_tools\models\funasr\damo\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-26 10:41:37,848 - modelscope - WARNING - No preprocessor field found in cfg.
2024-01-26 10:41:37,848 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-01-26 10:41:37,848 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\Bert-VITS2-2.3\\transcribe_tools\\models\\funasr\\damo\\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch'}. trying to build by task and model information.
2024-01-26 10:41:37,848 - modelscope - WARNING - No preprocessor key ('generic-asr', 'auto-speech-recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
2024-01-26 10:41:38,352 - modelscope - INFO - Model revision not specified, use revision: v1.2.0
2024-01-26 10:41:38,597 - modelscope - INFO - loading vad model from D:\Bert-VITS2-2.3\transcribe_tools\models\funasr\damo\speech_fsmn_vad_zh-cn-16k-common-pytorch ...
2024-01-26 10:41:38,927 - modelscope - INFO - Model revision not specified, use revision: v1.1.7
2024-01-26 10:41:39,228 - modelscope - INFO - loading punctuation model from D:\Bert-VITS2-2.3\transcribe_tools\models\funasr\damo\punc_ct-transformer_zh-cn-common-vocab272727-pytorch ...
Please install rotary_embedding_torch by:
 pip install -U rotary_embedding_torch
Please install rotary_embedding_torch by:
 pip install -U rotary_embedding_torch
Please install rotary_embedding_torch by:
 pip install -U rotary_embedding_torch
Please install rotary_embedding_torch by:
 pip install -U rotary_embedding_torch
Traceback (most recent call last):
  File "D:\Bert-VITS2-2.3\venv\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "D:\Bert-VITS2-2.3\venv\lib\site-packages\modelscope\pipelines\audio\asr_inference_pipeline.py", line 123, in __init__
    from funasr.bin import asr_inference_launch
ImportError: cannot import name 'asr_inference_launch' from 'funasr.bin' (D:\Bert-VITS2-2.3\venv\lib\site-packages\funasr\bin\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto_transcribe.py", line 22, in <module>
    from transcribe_tools.funasr_transcribe import run
  File "D:\Bert-VITS2-2.3\transcribe_tools\funasr_transcribe.py", line 6, in <module>
    from . import funasr_transcribe_one
  File "D:\Bert-VITS2-2.3\transcribe_tools\funasr_transcribe_one.py", line 10, in <module>
    inference_pipeline = pipeline(
  File "D:\Bert-VITS2-2.3\venv\lib\site-packages\modelscope\pipelines\builder.py", line 163, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\Bert-VITS2-2.3\venv\lib\site-packages\modelscope\pipelines\builder.py", line 67, in build_pipeline
    return build_from_cfg(
  File "D:\Bert-VITS2-2.3\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: AutomaticSpeechRecognitionPipeline: cannot import name 'asr_inference_launch' from 'funasr.bin' (D:\Bert-VITS2-2.3\venv\lib\site-packages\funasr\bin\__init__.py)

**Comment by YYuX-1145** [comment]
尝试：
```
%PYTHON% -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple funasr==0.8.7
```

**Comment by DoshideDK** [comment]
> 尝试：
> 
> ```
> %PYTHON% -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple funasr==0.8.7
> ```

可以了，感谢大佬。
