### ISSUE TITLE
为什么明明安装了modelscope，却一直提示没有modelscope ？

### ISSUE THREAD

**Issue by qling189** [YYuX-1145/Bert-VITS2-Integration-package#74]
Traceback (most recent call last):
  File "auto_transcribe.py", line 22, in <module>
    from transcribe_tools.funasr_transcribe import run
  File "E:\Tools\Bert-VITS2-2.3\transcribe_tools\funasr_transcribe.py", line 6, in <module>
    from . import funasr_transcribe_one
  File "E:\Tools\Bert-VITS2-2.3\transcribe_tools\funasr_transcribe_one.py", line 4, in <module>
    from modelscope.pipelines import pipeline
ModuleNotFoundError: No module named 'modelscope'

pip list 显示 modelscope  1.12.0

**Comment by YYuX-1145** [comment]
是否正确地安装到了整合包虚拟环境中而不是系统的python？
此外模块版本也不对...见requirements
