### ISSUE TITLE
首次训练报错：soundfile.LibsndfileError: <exception str() failed>

### ISSUE THREAD

**Issue by hiatus233** [YYuX-1145/Bert-VITS2-Integration-package#79]
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                           | 0/15 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "train_ms.py", line 840, in <module>
    run()
  File "train_ms.py", line 361, in run
    train_and_evaluate(
  File "train_ms.py", line 423, in train_and_evaluate
    for batch_idx, (
  File "E:\Bert-VITS2-2.3\Bert-VITS2-2.3\venv\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "E:\Bert-VITS2-2.3\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "E:\Bert-VITS2-2.3\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "E:\Bert-VITS2-2.3\Bert-VITS2-2.3\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "E:\Bert-VITS2-2.3\Bert-VITS2-2.3\venv\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
soundfile.LibsndfileError: <exception str() failed>

有无大佬知道这是为什么？打标的过程中出现繁中是影响吗？

**Comment by hiatus233** [comment]
初步感觉是数据集的问题，在减小数据集规模和去掉某些音频之后就没有这个报错了

**Comment by mortyzhou77** [comment]
请问您解决了这类问题吗
